# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Shiva Gaire - GeekSambhu
title: Programming Stuffs and Learning - Shiva Gaire
email: geeksambhu@gmail.com
description: This is the part of my day to day learning - Shiva Gaire #> # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.shivagaire.com.np" # the base hostname & protocol for your site, e.g. http://example.com
preview_image_url: https://avatars0.githubusercontent.com/u/9899283?v=3&s=460
twitter_username: geeksambhu
github_username: geeksambhu
linkedin_username: geeksambhu
facebook:
  appid: 831054347059208
so_nickname: geeksambhu
so_uid: 7306868
github:
  repository_name: geeksambhu
  project_tagline: A part of my continuous learning
# Build settings
highlighter: rouge
paginate: 5
paginate_path: "/blog/page:num"
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-last-modified-at
exclude:
  - Gemfile
  - Gemfile.lock
include: [".well-known"]